version: '3.9'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      REST_API_PORT: 5000
      MONGO_HOST: task_manager_mongo_db
  my_app_mongodb:
    image: mongo:5.0.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: task_manager_mongo_db